services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SpoonerWeb\BeSecurePw\:
    resource: '../Classes/*'

  SpoonerWeb\BeSecurePw\Database\Event\AddForceResetPasswordLinkEvent:
    tags:
      - name: event.listener
        identifier: 'addForceResetPasswordLink'

  SpoonerWeb\BeSecurePw\EventListener\AfterBackendPageRenderEventListener:
    tags:
      - name: event.listener
        identifier: 'be-secure-pw-after-backend-page-renderer-event'
        event: TYPO3\CMS\Backend\Controller\Event\AfterBackendPageRenderEvent